### ISSUE TITLE
Order of module mounts for assets is wrong

### ISSUE THREAD

**Issue by moebiusband73** [gethyas/doks#1122]
Not sure if this belongs here.

With the current  ./config/_default/module.toml it is not possible to overwrite parts of the doks theme because the local assets directory is mounted last. To allow overwrites it has to be mounted before the mounts in the doks-core folder.

**Comment by h-enk** [comment]
Can't replicate.

Added to `assets/scss/common/_variables-custom.scss`

```scss
// Put your custom SCSS variables here

$font-family-base:            var(--#{$prefix}font-monospace);
```

And, to `assets/scss/common/_custom.scss`:

```scss
// Put your custom SCSS code here

@include color-mode(dark) {
  body {
    background: blue;
  }
}
```

![Snag_29b9c3](https://github.com/gethyas/doks/assets/3902872/ba76938c-433f-4073-8e30-f931697beb8c)
