### ISSUE TITLE
Rendering broken on dark-theme cards

### ISSUE THREAD

**Issue by c4lliope** [gethyas/doks#1143]
Hello - here's an example using Doks on https://www.cloudhypervisor.org/ -
you can see the `.card` selector has precedence for rendering a dark font `color` rule, regardless of the dark background theme on the page.

![image](https://github.com/gethyas/doks/assets/30454698/ec473d16-5368-42e0-8ddb-850c6d0e0394)

**Comment by h-enk** [comment]
Add `color: $body-color-dark;` to `assets/scss/common/_dark.scss` — see also https://github.com/cloud-hypervisor/cloud-hypervisor.github.io/blob/main/assets/scss/common/_dark.scss#L379-L382 — and you're good to go

```scss
[data-dark-mode] body .card {
  background: $body-bg-dark;
  border: 1px solid $border-dark;
  color: $body-color-dark;
}
```
