### ISSUE TITLE
Terms list does not display title

### ISSUE THREAD

**Issue by h-enk** [gethyas/doks#1254]
- Copy `node_modules/@hyas/doks-core/layouts/blog/single.html` and paste as `layouts/blog/single.html`. Update the latter (line 15) with something like:

    ```html
    <div class="col-md-13">
    ```
- Add to `assets/scss/common/_custom.scss` something like:
    ```scss
    .single.blog .content,
    .list.blog .content {
      font-size: $font-size-base * 1.375;
    }
    ```

- That's a bug — thx! Will be fixed. Quick fix for now: copy `node_modules/@hyas/doks-core/layouts/_default/terms.html` and paste as `layouts/_default/terms.html`.  Update the latter (line 12) with:
```html
              <a class="stretched-link" href="{{ .RelPermalink }}">{{ .Title }} &rarr;</a>
```

_Originally posted by @h-enk in https://github.com/gethyas/doks/discussions/1252#discussioncomment-9791648_
